name: pdp_quiz_app_backand
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

dependencies:
  args: ^2.3.0
  crypto: ^3.0.3
  http: ^1.2.2
  postgres: ^3.2.1
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.0
  uuid: ^4.4.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
